apiVersion: v1
kind: Service
metadata:
  name: jmeter-prod
  namespace: jmeter
  labels:
    app: jmeter-prod
spec:
  type: NodePort
  ports:
    - port: 9270
      targetPort: 9270
      nodePort: 30002
      name: smarttuning
  selector:
    app: jmeter-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  annotations:
    reloader.stakater.com/auto: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9270"
  labels:
    app: jmeter-prod
  name: jmeter-prod
  namespace: jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jmeter-prod
    spec:
      containers:
      - image: wellisonraul/dynamic_jmeter:0.0.45
        name: dynamic-jmeter
        ports:
          - containerPort: 9270
            name: http
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: jmeter-config
      restartPolicy: Always
