---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: cars-v1
  namespace: travel-agency
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cars-v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
     - type: Resource
       resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 80
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: discounts-v1
  namespace: travel-agency
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: discounts-v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
     - type: Resource
       resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 80
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: flights-v1
  namespace: travel-agency
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flights-v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
     - type: Resource
       resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 80
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: hotels-v1
  namespace: travel-agency
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hotels-v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
     - type: Resource
       resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 80
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: insurances-v1
  namespace: travel-agency
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: insurances-v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
     - type: Resource
       resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 80
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: travels-v1
  namespace: travel-agency
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: travels-v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
     - type: Resource
       resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 80

