---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: cartservice
  namespace: default
spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: Deployment
    name: cartservice
  # autoscale between 1 and 10 replicas
  # cluster supports at most 24 cores
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
     - type: Resource
       resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 80

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: checkoutservice
  namespace: default
spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: Deployment
    name: checkoutservice
  # autoscale between 1 and 10 replicas
  # cluster supports at most 24 cores
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
     - type: Resource
       resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 80


---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: currencyservice
  namespace: default
spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: Deployment
    name: currencyservice
  # autoscale between 1 and 10 replicas
  # cluster supports at most 24 cores
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
     - type: Resource
       resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 80

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: frontend
  namespace: default
spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  # autoscale between 1 and 10 replicas
  # cluster supports at most 24 cores
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
     - type: Resource
       resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 80

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: productcatalogservice
  namespace: default
spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: Deployment
    name: productcatalogservice
  # autoscale between 1 and 10 replicas
  # cluster supports at most 24 cores
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
     - type: Resource
       resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 80

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: recommendationservice
  namespace: default
spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: Deployment
    name: recommendationservice
  # autoscale between 1 and 10 replicas
  # cluster supports at most 24 cores
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
     - type: Resource
       resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 80
