apiVersion: v1
kind: ConfigMap
metadata:
  name: daytrader-config-jvm
  namespace: daytrader
data:
  jvm.options: |-
    -XX:+UseContainerSupport
    -Xgcpolicy:gencon
    -Xtune:virtualized
    -XX:MaxRAMPercentage=50
