apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-predictkube-secret
  namespace: quarkus
spec:
  secretTargetRef:
  - parameter: apiKey
    name: predictkube-secrets
    key: apiKey
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: quarkus-service-scaler
  namespace: quarkus
spec:
  scaleTargetRef:
    name: quarkus-service
  pollingInterval: 15
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: predictkube
    metadata:
      predictHorizon: "1m"
      historyTimeWindow: "12h"  # We recomend to use minimum 7-14 days time window as historical data
      prometheusAddress: http://prometheus-service.monitoring.svc.cluster.local:9090
      query: sum(rate(container_cpu_usage_seconds_total{id=~".*kubepods.*", namespace="quarkus", pod=~"quarkus-service.*", name!~".*POD.*", container!=""}[1m]))
      queryStep: "1m" # Note: query step duration for range prometheus queries
      threshold: '0.8' # Value to start scaling for
    authenticationRef:
      name: keda-trigger-auth-predictkube-secret
